name: Sync Tenant Repo to Main Repo
 
on:
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Swa-DevOps/CM-AEM-MAIN
          ref: refs/heads/cm/qa
 
      - name: Check if subtree exists
        run: |
          if git log --pretty=%B | grep -q "Add subtree from tenant repo"; then
            echo "Subtree already added"
            exit 0
          fi
          echo "Subtree not added yet"
 
      - name: Add tenant repo as subtree
        if: success() && ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git remote add -f tenant_repo https://github.com/Swa-DevOps/CM-AEM-TONOMOUS.git
          git subtree add --prefix=tenant_directory tenant_repo cm/qa --squash
          git commit -am "Add subtree from tenant repo"
          git push origin cm/qa
 
      - name: Pull latest changes from tenant repo
        run: |
          git subtree pull --prefix=tenant_directory tenant_repo cm/qa --squash
          git commit -am "Pull latest changes from tenant repo"
          git push origin cm/qa
