name: Sync Tenant Repo to Main Repo
 
on:
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Swa-DevOps/CM-AEM-MAIN
          ref: refs/heads/cm/qa
 
      - name: Check if subtree exists
        run: |
          if git log --pretty=%B | grep -q "Add subtree from tenant repo"; then
            echo "Subtree already added"
            exit 0
          fi
          echo "Subtree not added yet"
 
 
      - name: Pull latest changes from tenant repo
        run: |
          git config --global user.email "bute.swarup@gmail.com"
          git config --global user.name "Swa-DevOps"
          git subtree pull --prefix=tenant_directory https://github.com/Swa-DevOps/CM-AEM-TEST.git cm/qa --squash
          git commit -am "Pull latest changes from tenant repo"
          git push https://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@github.com/Swa-DevOps/CM-AEM-MAIN.git
