name: Test First time subtree and teenant add

on:
  workflow_dispatch:
    inputs:
      REPO:
        description: "Specify Tenant Repo" #e.g., CM-AEM-TONOMUS
        required: true
      BRANCH:
        description: "Specify Branch Name"
        required: true
      
jobs:
  subtree_to_aem_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Swa-DevOps/CM-AEM-MAIN
          ref: refs/heads/${{ inputs.BRANCH }} 
          
      - name: adding tenant repo
        run: |
          #git remote add ${{ inputs.REPO }} https://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@github.com/Swa-DevOps/${{ inputs.REPO }}.git --track ${{ inputs.BRANCH }} 
          #git fetch ${{ inputs.REPO }}
          
      - name: Subtree
        run: |
          git config --global user.email "bute.swarup@gmail.com"
          git config --global user.name "swarup"
          #git subtree add --prefix=${{ inputs.REPO }} https://github.com/Swa-DevOps/${{ inputs.REPO }}.git ${{ inputs.BRANCH }} --squash
          git subtree pull --prefix=${{ inputs.REPO }} https://github.com/Swa-DevOps/${{ inputs.REPO }}.git ${{ inputs.BRANCH }} --squash
          git push origin HEAD:${{ inputs.BRANCH }}
          
       
      - name: Push changes to AEM Main Repo
        run: |
          #git push https://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@github.com/Swa-DevOps/CM-AEM-MAIN.git ${{ inputs.BRANCH }}  
