name:  AEM Main Repo

on:
  workflow_dispatch:
    inputs:
      REPO:
        description: "Specify Tenant"
        required: true
jobs:
  subtree_to_aem_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Swa-DevOps/CM-AEM-MAIN
          ref: refs/heads/cm/qa 

      - name: Subtree
        run: |
          git config --global user.email "bute.swarup@gmail.com"
          git config --global user.name "swarup"
          git subtree  pull --prefix=tonomus https://github.com/Swa-DevOps/CM-AEM-TONOMUS.git cm/qa eb1706f171fa79991747641c9abcf518d597847f -squash

      - name: Push changes to AEM Main Repo
        run: |
          git push https://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@github.com/Swa-DevOps/CM-AEM-MAIN.git cm/qa 
