name: TEST Push subtree changes to AEM repo

on:
  workflow_dispatch:
    inputs:
      REPO:
        description: "Specify Tenant Repo" #e.g., CM-AEM-TONOMUS
        required: true
      BRANCH:
        description: "Specify Branch Name"
        required: true
      ACTION:
        description: "Action Message"
        required: true

jobs:
  subtree_to_aem_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Swa-DevOps/CM-AEM-MAIN
          ref: refs/heads/${{ inputs.BRANCH }}  

      - name: Add remote and fetch tenant repo
        run: |
          git config --global user.email "bute.swarup@gmail.com"
          git config --global user.name "swarup"
          git pull origin ${{ inputs.BRANCH }}
          #git remote add -f ${{ inputs.REPO }} https://github.com/Swa-DevOps/CM-AEM-${{ inputs.REPO }}.git
      
      - name: Subtree 
        uses: Swa-DevOps/subtree
        with:
          pat: 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
          repo: https://github.com/Swa-DevOps/CM-AEM-${{ inputs.REPO }}.git
          action: ${{ inputs.ACTION }}
          prefix: swa-devops
          message: Custom Commit Message
