name: v3 Sync Tenant Repo to Main Repo
 
on:
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
 
      - name: Clone scripts branch
        run: |
          mkdir -p scripts_folder
          git clone --scripts --single-branch https://github.com/Swa-DevOps/aem-guides-wknd.git scripts_folder/
          pwd && ll scripts_folder/
          mv scripts_folder/* .
          pwd && ll
 
      - name: Run sonar
        run: |
          ll 
          chmod +x sonar-scan.sh && bash sonar-scan.sh
