name: v3 Sync Tenant Repo to Main Repo 

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout script
        uses: actions/checkout@v2
        with:
          repository: Swa-DevOps/aem-guides-wknd
          ref: refs/heads/scripts

      - name: Run sonar
        run: |
          chmod +x sonar-scan.sh && bash sonar-scan.sh
