name: v2 Sync Tenant Repo to Main Repo 

on:
  workflow_dispatch:
    inputs:
      REPO:
        description: "Specify repo"
        required: true
      BRANCH:
        description: "Specify Branch"
        required: true
      PREFIX:
        description: "Specify prefix"
        required: true
      ACTION:
        description: "Specify Action pull / add"
        required: true
        
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:


      - name: subtree
        run: |
          chmod +x .github/workflows/subtreev2.sh && pwd && bash .github/workflows/subtreev2.sh $repo $branch $prefix $action
        env:
          repo: ${{ inputs.REPO }}
          branch: ${{ inputs.BRANCH }}
          prefix: ${{ inputs.PREFIX }}
          action: ${{ inputs.ACTION }}
